// Pure render functions — no I/O. Reproduce the hand-written page structure
// in signals/*.html and index.html exactly; only the data is now dynamic.

const GENERATED_NOTICE =
  "<!-- AUTO-GENERATED by scripts/generate-site.mjs — edits here will be overwritten on next publish. Edit content via the dashboard instead. -->";

export function escapeHtml(str) {
  return str
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

/** Plain-text body copy -> paragraph HTML. Blank line = new paragraph, **bold** = <strong>. */
export function renderBodyCopy(bodyCopy) {
  return bodyCopy
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => {
      const escaped = escapeHtml(p).replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
      return `    <p>${escaped}</p>`;
    })
    .join("\n");
}

const TIER_LABEL = { 1: "Tier 1", "1": "Tier 1", 2: "Tier 2", "2": "Tier 2", 3: "Tier 3", "3": "Tier 3" };

function renderEvidenceItem(item) {
  return `      <li class="evidence-item">
        <span class="evidence-tier pill">${TIER_LABEL[item.tier]}</span>
        <span class="evidence-text">
          ${escapeHtml(item.source_name)}
          <span class="evidence-direction">${escapeHtml(item.description)}</span>
        </span>
      </li>`;
}

function renderInline(text) {
  return escapeHtml(text).replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
}

function renderClaimCard(claimCopy) {
  if (!claimCopy) return "";
  return `
  <div class="card">
    <p class="card-label">${escapeHtml(claimCopy.label)}</p>
    <p class="card-text">${renderInline(claimCopy.claimText)}</p>
    <p class="card-status${claimCopy.isMissed ? " missed" : ""}">${escapeHtml(claimCopy.statusText)}</p>
  </div>`;
}

const CONFIDENCE_LABEL = { low: "Low", moderate: "Moderate", high: "High", collapsed: "Collapsed" };
const VELOCITY_LABEL = { rising: "Rising", falling: "Falling", steady: "Steady" };

/**
 * Renders one signal page. Phase 1 only: a single narrative state (matching
 * Ford/Gen Z's structure exactly). Multiple story-arc states with the
 * segmented then/now control (Reflecting Pool) is Phase 3 dashboard scope —
 * this function intentionally doesn't try to guess that shape yet.
 */
export function renderSignalPage({ signal, categoryLabel, eyebrowLabel, bodyCopy, watchingText, evidence, clusterCount, claimCopy }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(signal.title)} — Scattered Signals</title>${signal.meta_description ? `\n<meta name="description" content="${escapeHtml(signal.meta_description)}">` : ""}
<link rel="stylesheet" href="../css/style.css">
</head>
<body>
${GENERATED_NOTICE}

<header class="site-header">
  <div class="site-header-inner">
    <a class="wordmark" href="../index.html">Scattered Signals</a>
    <nav class="site-nav">
      <a href="../index.html">Signals</a>
      <a href="../about.html">About</a>
    </nav>
  </div>
</header>

<main>
  <a class="back-link" href="../index.html">All Signals</a>

  <div class="signal-header">
    <p class="eyebrow">${escapeHtml(categoryLabel)} · ${escapeHtml(eyebrowLabel)}</p>
    <h1>${escapeHtml(signal.title)}</h1>
  </div>

  <div class="meta-row">
    <div class="meta-item">
      <span class="label">Confidence</span>
      <span class="value">${CONFIDENCE_LABEL[signal.confidence]}</span>
    </div>
    <div class="meta-item">
      <span class="label">Velocity</span>
      <span class="value">${VELOCITY_LABEL[signal.velocity]}</span>
    </div>
    <div class="meta-item">
      <span class="label">Clusters</span>
      <span class="value">${clusterCount}</span>
    </div>
  </div>

  <div class="body-copy">
${renderBodyCopy(bodyCopy)}
  </div>
${renderClaimCard(claimCopy)}

  <div class="evidence-section">
    <h2 class="section-heading">Supporting Evidence</h2>
    <ul class="evidence-list">
${evidence.map(renderEvidenceItem).join("\n")}
    </ul>
  </div>

  ${watchingText ? `<div class="watching">
    <h2 class="section-heading">What We're Watching</h2>
    <p>${escapeHtml(watchingText)}</p>
  </div>` : ""}
</main>

<footer class="site-footer">
  <div class="site-footer-inner">
    <p>Scattered Signals — context, not content.</p>
  </div>
</footer>

</body>
</html>
`;
}

function categorySlugForFilter(categorySlug) {
  return categorySlug;
}

function renderSignalRow({ signal, categoryLabel, categorySlug, statusPill }) {
  const statusHtml =
    statusPill.variant === "ongoing"
      ? `<span class="pill">${escapeHtml(statusPill.label)}</span>`
      : `<span class="status-pill ${statusPill.variant}">${escapeHtml(statusPill.label)}</span>`;

  return `      <li data-category="${escapeHtml(categorySlugForFilter(categorySlug))}" data-top="${signal.is_top}">
        <a class="signal-row" href="signals/${escapeHtml(signal.slug)}.html">
          <div>
            <p class="signal-row-title">${escapeHtml(signal.title)}</p>
            <p class="signal-row-meta">${escapeHtml(categoryLabel)} · ${escapeHtml(signal.homepage_meta)}</p>
          </div>
          <div class="signal-row-status">${statusHtml}</div>
        </a>
      </li>`;
}

/**
 * Regenerates index.html. The hero copy is a fixed template constant, not
 * data-driven (there's no site-copy table yet) — edit it here, not by hand
 * on the generated file. Only the filter pills + signal list are dynamic.
 */
export function renderIndexPage({ rows, categories }) {
  const categoryPills = categories
    .map((c) => `      <button class="filter-pill" data-category="${escapeHtml(c.slug)}" role="tab" aria-selected="false">${escapeHtml(c.label)}</button>`)
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Scattered Signals</title>
<link rel="stylesheet" href="css/style.css">
</head>
<body>
${GENERATED_NOTICE}

<header class="site-header">
  <div class="site-header-inner">
    <a class="wordmark" href="index.html">Scattered Signals</a>
    <nav class="site-nav">
      <a href="index.html">Signals</a>
      <a href="about.html">About</a>
    </nav>
  </div>
</header>

<main>
  <section class="hero">
    <h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h1>
    <p class="hero-sub">Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam.</p>
  </section>

  <section>
    <div class="filter-pills" role="tablist" aria-label="Filter signals">
      <button class="filter-pill" data-category="top" role="tab" aria-selected="false">Top</button>
      <button class="filter-pill active" data-category="all" role="tab" aria-selected="true">All</button>
${categoryPills}
    </div>

    <h2 class="section-heading">News</h2>
    <ul class="signal-index">
${rows.map(renderSignalRow).join("\n")}
    </ul>
    <p class="empty-state" hidden>No signals in this category yet.</p>
  </section>
</main>

<footer class="site-footer">
  <div class="site-footer-inner">
    <p>Scattered Signals — context, not content.</p>
    <p>Every signal here is a living page. Evidence accumulates, confidence updates, nothing is finished.</p>
  </div>
</footer>

<script src="js/filter.js"></script>
</body>
</html>
`;
}
