// Pure render functions — no I/O. Reproduce the hand-written page structure
// in topics/*.html and index.html exactly; only the data is now dynamic.

const GENERATED_NOTICE =
  "<!-- AUTO-GENERATED by scripts/generate-site.mjs — edits here will be overwritten on next publish. Edit content via the dashboard instead. -->";

export function escapeHtml(str) {
  return str
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

/** Plain-text body copy -> paragraph HTML. Blank line = new paragraph, **bold** = <strong>. */
export function renderBodyCopy(bodyCopy) {
  return bodyCopy
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => {
      const escaped = escapeHtml(p).replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
      return `    <p>${escaped}</p>`;
    })
    .join("\n");
}

const TIER_LABEL = { 1: "Tier 1", "1": "Tier 1", 2: "Tier 2", "2": "Tier 2", 3: "Tier 3", "3": "Tier 3" };

/** Same "Mon DD, YYYY" shape used on the chart's point labels, so a reader can match one to the other at a glance. */
function formatEvidenceDate(isoDate) {
  return new Date(isoDate).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

/** number = this item's position in the evidence list, 1-based — matches the numbered dot on the chart above. */
function renderEvidenceItem(item, number) {
  const dateLabel = formatEvidenceDate(item.source_published_at ?? item.created_at);
  return `      <li class="evidence-item">
        <span class="evidence-number">${number}</span>
        <span class="evidence-tier pill">${TIER_LABEL[item.tier]}</span>
        <span class="evidence-text">
          ${escapeHtml(item.source_name)}<span class="evidence-date">${escapeHtml(dateLabel)}</span>
          <span class="evidence-direction">${escapeHtml(item.description)}</span>
        </span>
      </li>`;
}

const EVIDENCE_VISIBLE_MAX = 3;

/**
 * First 3 evidence items always visible; the rest sit behind a native
 * <details> accordion. Numbers are the item's position in this list
 * (stable regardless of chart order) — renderChartSection uses the same
 * numbers so a reader can match a dot back to its source.
 */
function renderEvidenceSection(evidence) {
  const numbered = evidence.map((item, i) => ({ item, number: i + 1 }));
  const visible = numbered.slice(0, EVIDENCE_VISIBLE_MAX);
  const hidden = numbered.slice(EVIDENCE_VISIBLE_MAX);

  const visibleHtml = `    <ul class="evidence-list">
${visible.map(({ item, number }) => renderEvidenceItem(item, number)).join("\n")}
    </ul>`;

  if (hidden.length === 0) return visibleHtml;

  return `${visibleHtml}
    <details class="evidence-more">
      <summary>Show ${hidden.length} more</summary>
      <ul class="evidence-list">
${hidden.map(({ item, number }) => renderEvidenceItem(item, number)).join("\n")}
      </ul>
    </details>`;
}

const PREMISE_STRENGTH_TICKS = [
  { value: 3, label: "High" },
  { value: 2, label: "Moderate" },
  { value: 1, label: "Low" },
  { value: 0, label: "Collapsed" },
];

/**
 * Chart points come pre-computed (evidenceToChartPoints from packages/core)
 * — this just draws them. `evidence` is the same array/order used to
 * number the evidence list below, so each dot can be labeled with the same
 * number as its source in that list — otherwise there's no way to tell
 * which dot is which source.
 */
function renderChartSection(chartPoints, evidence) {
  if (chartPoints.length === 0) return "";

  const numberByEvidenceId = new Map(evidence.map((item, i) => [item.id, i + 1]));

  const PLOT_LEFT = 92;
  const PLOT_RIGHT = 580;
  const toY = (y) => 120 - (y / 3) * 100; // 0..3 scale -> 120..20 px within a 140-tall viewBox

  const points = chartPoints.map((p) => ({
    ...p,
    px: PLOT_LEFT + p.x * (PLOT_RIGHT - PLOT_LEFT),
    py: toY(p.y),
  }));

  // AI-researched drafts can carry far more evidence than a hand-curated
  // signal ever would (20+ sources isn't unusual) — shrinking the dots once
  // there are a lot of them keeps overlapping circles from fusing into an
  // unreadable blob, even though genuinely same-date points will still
  // touch (there's no false x-position to give them; the date is real).
  const DENSE_THRESHOLD = 12;
  const isDense = points.length > DENSE_THRESHOLD;
  const circleRadius = isDense ? 6 : 9;
  const circleFontSize = isDense ? 8 : 10;

  const polyline = points.map((p) => `${p.px.toFixed(1)},${p.py.toFixed(1)}`).join(" ");
  const circles = points
    .map((p) => {
      const number = numberByEvidenceId.get(p.evidenceId);
      return `      <circle cx="${p.px.toFixed(1)}" cy="${p.py.toFixed(1)}" r="${circleRadius}" fill="#1d1d1f"/>
      <text x="${p.px.toFixed(1)}" y="${(p.py + circleFontSize / 3).toFixed(1)}" text-anchor="middle" font-size="${circleFontSize}" font-weight="600" fill="#ffffff">${number}</text>`;
    })
    .join("\n");

  const axis = `      <line x1="${PLOT_LEFT}" y1="15" x2="${PLOT_LEFT}" y2="125" stroke="#d2d2d7" stroke-width="1"/>
${PREMISE_STRENGTH_TICKS.map(
    (t) => `      <text x="${PLOT_LEFT - 10}" y="${toY(t.value) + 4}" text-anchor="end" font-size="11" fill="#86868b">${t.label}</text>`,
  ).join("\n")}`;

  // Row assignment based on each label's actual left/right extent (which
  // depends on its alignment — a right-aligned label extends leftward from
  // its dot, not rightward), not just dot-to-dot distance. A simple gap
  // check on dot position alone under-counts overlap for edge labels.
  // Labels are date-only — the full source name is one scroll away in the
  // evidence list, and cramming it into the chart is what caused the
  // clutter in the first place.
  //
  // With enough points, there just isn't room for every label without
  // overlapping regardless of row count — forcing one in anyway (the old
  // behavior: reuse whichever row has the least-bad overlap) produced
  // garbled, stacked text. Skipping a label once no free row exists is the
  // fix: that point's numbered dot is still on the chart, and every date is
  // still in the evidence list below — nothing is lost, just not force-fit
  // into an illegible spot.
  const ROW_HEIGHT = 20;
  const ROW_COUNT = isDense ? 5 : 3;
  const LABEL_WIDTH = 100; // wide enough for "N Mon DD, YYYY" on one line at 11.5px
  const PADDING = 10;
  const rowRightEdge = new Array(ROW_COUNT).fill(-Infinity);

  const labels = points
    .map((p, i) => {
      const isFirst = i === 0;
      const isLast = i === points.length - 1;
      const align = isFirst ? "left" : isLast ? "right" : "center";
      const translate = isFirst ? "0" : isLast ? "-100%" : "-50%";

      const left = isFirst ? p.px : isLast ? p.px - LABEL_WIDTH : p.px - LABEL_WIDTH / 2;
      const right = isFirst ? p.px + LABEL_WIDTH : isLast ? p.px : p.px + LABEL_WIDTH / 2;

      const row = rowRightEdge.findIndex((edge) => left >= edge + PADDING);
      if (row === -1) return null; // no free row — drop the label, keep the dot
      rowRightEdge[row] = right;

      const dateLabel = formatEvidenceDate(p.isoDate);
      const number = numberByEvidenceId.get(p.evidenceId);
      return `      <div class="chart-point-label" style="left:${((p.px / 600) * 100).toFixed(2)}%; top:${row * ROW_HEIGHT}px; text-align:${align}; transform:translateX(${translate});"><strong>${number}</strong> ${escapeHtml(dateLabel)}</div>`;
    })
    .filter(Boolean)
    .join("\n");

  return `
  <div class="chart-section">
    <h2 class="section-heading">Evidence Strength Over Time</h2>
    <p class="chart-caption">Rising means the evidence is accumulating in support of the premise. Falling means it's moving against it.</p>
    <svg viewBox="0 0 600 140" preserveAspectRatio="none">
${axis}
      <polyline points="${polyline}" fill="none" stroke="#1d1d1f" stroke-width="2"/>
${circles}
    </svg>
    <div class="chart-point-labels" style="height:${ROW_COUNT * ROW_HEIGHT + 12}px;">
${labels}
    </div>
  </div>`;
}

function renderInline(text) {
  return escapeHtml(text).replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
}

function renderClaimCard(claimCopy) {
  if (!claimCopy) return "";
  return `
  <div class="card">
    <p class="card-label">${escapeHtml(claimCopy.label)}</p>
    <p class="card-text">${renderInline(claimCopy.claimText)}</p>
    <p class="card-status${claimCopy.isMissed ? " missed" : ""}">${escapeHtml(claimCopy.statusText)}</p>
  </div>`;
}

const CONFIDENCE_LABEL = { low: "Low", moderate: "Moderate", high: "High", collapsed: "Collapsed" };
const VELOCITY_LABEL = { rising: "Rising", falling: "Falling", steady: "Steady" };

/**
 * Renders one signal page. Phase 1 only: a single narrative state (matching
 * Ford/Gen Z's structure exactly). Multiple story-arc states with the
 * segmented then/now control (Reflecting Pool) is Phase 3 dashboard scope —
 * this function intentionally doesn't try to guess that shape yet.
 */
export function renderSignalPage({ signal, categoryLabel, eyebrowLabel, bodyCopy, watchingText, evidence, clusterCount, claimCopy, premiseStrength, chartPoints }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(signal.title)} — Plotlines</title>${signal.meta_description ? `\n<meta name="description" content="${escapeHtml(signal.meta_description)}">` : ""}
<link rel="stylesheet" href="../css/style.css">
</head>
<body>
${GENERATED_NOTICE}

<header class="site-header">
  <div class="site-header-inner">
    <a class="wordmark" href="../index.html">Plotlines</a>
    <nav class="site-nav">
      <a href="../about.html">About</a>
    </nav>
  </div>
</header>

<main>
  <a class="back-link" href="../index.html">All Topics</a>

  <div class="signal-header">
    <p class="eyebrow">${escapeHtml(categoryLabel)} · ${escapeHtml(eyebrowLabel)}</p>
    <h1>${escapeHtml(signal.title)}</h1>
  </div>

  <div class="meta-row">
    <div class="meta-item">
      <span class="label">Evidence Strength</span>
      <span class="value">${CONFIDENCE_LABEL[premiseStrength]}</span>
    </div>
    <div class="meta-item">
      <span class="label">Velocity</span>
      <span class="value">${VELOCITY_LABEL[signal.velocity]}</span>
    </div>
    <div class="meta-item">
      <span class="label">Clusters</span>
      <span class="value">${clusterCount}</span>
    </div>
  </div>

  <div class="body-copy">
${renderBodyCopy(bodyCopy)}
  </div>
${renderChartSection(chartPoints, evidence)}
${renderClaimCard(claimCopy)}

  <div class="evidence-section">
    <h2 class="section-heading">Supporting Evidence</h2>
${renderEvidenceSection(evidence)}
  </div>

  ${watchingText ? `<div class="watching">
    <h2 class="section-heading">What We're Watching</h2>
    <p>${escapeHtml(watchingText)}</p>
  </div>` : ""}
</main>

<footer class="site-footer">
  <div class="site-footer-inner">
    <p>© 2026 Plotlines</p>
    <nav class="footer-nav">
      <a href="../terms.html">Terms</a>
      <a href="../privacy.html">Privacy</a>
    </nav>
  </div>
</footer>

</body>
</html>
`;
}

function categorySlugForFilter(categorySlug) {
  return categorySlug;
}

function renderSignalRow({ signal, categoryLabel, categorySlug, statusPill }) {
  const statusHtml =
    statusPill.variant === "ongoing"
      ? `<span class="pill">${escapeHtml(statusPill.label)}</span>`
      : `<span class="status-pill ${statusPill.variant}">${escapeHtml(statusPill.label)}</span>`;

  return `      <li data-category="${escapeHtml(categorySlugForFilter(categorySlug))}" data-top="${signal.is_top}">
        <a class="signal-row" href="topics/${escapeHtml(signal.slug)}.html">
          <div class="signal-row-main">
            <p class="signal-row-title">${escapeHtml(signal.title)}</p>
            <p class="signal-row-meta">${escapeHtml(categoryLabel)} · ${escapeHtml(signal.homepage_meta)}</p>
          </div>
          <div class="signal-row-status">${statusHtml}</div>
        </a>
      </li>`;
}

/**
 * Regenerates index.html. The hero copy is a fixed template constant, not
 * data-driven (there's no site-copy table yet) — edit it here, not by hand
 * on the generated file. Only the filter pills + signal list are dynamic.
 *
 * Pills are only rendered for categories with at least one published signal
 * — the categories table can carry far more rows than are in use at any
 * given time (seeded ahead of content so the dashboard's category picker is
 * ready when a new beat gets its first signal), and a row of pills that
 * mostly lead to "No topics in this category yet" would just be clutter.
 */
export function renderIndexPage({ rows, categories }) {
  const usedSlugs = new Set(rows.map((r) => r.categorySlug));
  const categoryPills = categories
    .filter((c) => usedSlugs.has(c.slug))
    .map((c) => `      <button class="filter-pill" data-category="${escapeHtml(c.slug)}" role="tab" aria-selected="false">${escapeHtml(c.label)}</button>`)
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Plotlines</title>
<link rel="stylesheet" href="css/style.css">
</head>
<body>
${GENERATED_NOTICE}

<header class="site-header">
  <div class="site-header-inner">
    <a class="wordmark" href="index.html">Plotlines</a>
    <nav class="site-nav">
      <a href="about.html">About</a>
    </nav>
  </div>
</header>

<main>
  <section class="hero">
    <h1>Follow the plot.</h1>
    <p class="hero-sub">Not the news cycle.</p>
  </section>

  <section>
    <div class="filter-pills" role="tablist" aria-label="Filter topics">
      <button class="filter-pill" data-category="top" role="tab" aria-selected="false">Trending</button>
      <button class="filter-pill active" data-category="all" role="tab" aria-selected="true">All</button>
${categoryPills}
    </div>

    <h2 class="section-heading">Topics</h2>
    <ul class="signal-index">
${rows.map(renderSignalRow).join("\n")}
    </ul>
    <p class="empty-state" hidden>No topics in this category yet.</p>
  </section>
</main>

<footer class="site-footer">
  <div class="site-footer-inner">
    <p>© 2026 Plotlines</p>
    <nav class="footer-nav">
      <a href="terms.html">Terms</a>
      <a href="privacy.html">Privacy</a>
    </nav>
  </div>
</footer>

<script src="js/filter.js"></script>
</body>
</html>
`;
}
